services:
  - type: web
    name: multimedia-hub
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: PYTHON_VERSION
        value: 3.11
    buildFilter:
      paths:
        - backend/**  # trigger builds only when backend changes
    rootDir: backend  # 🔥 THIS IS THE FIX — tell Render where to start
